# Generated by Django 5.1.7 on 2025-03-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='published_at',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
