# Generated by Django 5.1.7 on 2025-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
